//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("admin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Form1_button2_Click_Error {
            get {
                return ResourceManager.GetString("Form1_button2_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil input.
        /// </summary>
        internal static string Form1_button2_Click_Feil_input {
            get {
                return ResourceManager.GetString("Form1_button2_Click_Feil_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klarte ikke å utføre reservasjon, kontakt support..
        /// </summary>
        internal static string Form1_button2_Click_kontakt_support {
            get {
                return ResourceManager.GetString("Form1_button2_Click_kontakt_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangler adresse.
        /// </summary>
        internal static string Form1_button2_Click_Mangler_adresse {
            get {
                return ResourceManager.GetString("Form1_button2_Click_Mangler_adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangler brukernavn.
        /// </summary>
        internal static string Form1_button2_Click_Mangler_brukernavn {
            get {
                return ResourceManager.GetString("Form1_button2_Click_Mangler_brukernavn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mangler telefon nr.
        /// </summary>
        internal static string Form1_button2_Click_Mangler_telefon_nr {
            get {
                return ResourceManager.GetString("Form1_button2_Click_Mangler_telefon_nr", resourceCulture);
            }
        }
    }
}
